// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type StopRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty" xml:"status,omitempty" mapstructure:"status"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty" xml:"message,omitempty" mapstructure:"message"`
	SomeOther            string   `protobuf:"bytes,3,opt,name=some_other,json=someOther,proto3" json:"some_other,omitempty" xml:"some_other,omitempty" mapstructure:"some_other"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StopRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StopRequest) GetSomeOther() string {
	if m != nil {
		return m.SomeOther
	}
	return ""
}

type StopResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StopResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VersionRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Boolean              bool     `protobuf:"varint,2,opt,name=boolean,proto3" json:"boolean,omitempty" xml:"boolean,omitempty" mapstructure:"boolean"`
	Integer              uint32   `protobuf:"varint,3,opt,name=integer,proto3" json:"integer,omitempty" xml:"integer,omitempty" mapstructure:"integer"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}
func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func (m *VersionRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VersionRequest) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *VersionRequest) GetInteger() uint32 {
	if m != nil {
		return m.Integer
	}
	return 0
}

type VersionResponse struct {
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" xml:"version,omitempty" mapstructure:"version"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{3}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*StopRequest)(nil), "example.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "example.StopResponse")
	proto.RegisterType((*VersionRequest)(nil), "example.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "example.VersionResponse")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xb4, 0x55, 0x1a, 0xf3, 0xb4, 0x0a, 0x8b, 0xd5, 0xa5, 0x20, 0x48, 0x4e, 0x82, 0x50, 0x41,
	0xf1, 0x2a, 0x05, 0x7b, 0xf1, 0x24, 0xa4, 0xe0, 0x49, 0x94, 0x54, 0xa6, 0x31, 0x90, 0xec, 0x8b,
	0xd9, 0x4d, 0xf1, 0x37, 0xf8, 0xab, 0x25, 0x9b, 0xdd, 0xe0, 0x07, 0x05, 0xf5, 0xb4, 0xcc, 0xcc,
	0xee, 0xbc, 0x99, 0xc7, 0xd2, 0x08, 0x6f, 0x49, 0x51, 0xe6, 0x38, 0x77, 0xe7, 0xa4, 0xac, 0xd8,
	0xb0, 0x08, 0x1c, 0x8c, 0x1e, 0x69, 0x67, 0x6e, 0xb8, 0x8c, 0xf1, 0x5a, 0x43, 0x1b, 0x71, 0x48,
	0x03, 0x6d, 0x12, 0x53, 0x6b, 0xd9, 0x3b, 0xe9, 0x9d, 0x86, 0xb1, 0x43, 0x42, 0x52, 0x50, 0x40,
	0xeb, 0x24, 0x85, 0xec, 0x5b, 0xc1, 0x43, 0x71, 0x4c, 0xa4, 0xb9, 0xc0, 0x13, 0x9b, 0x17, 0x54,
	0x72, 0xd3, 0x8a, 0x61, 0xc3, 0xdc, 0x35, 0x44, 0x34, 0xa5, 0xdd, 0xd6, 0x5f, 0x97, 0xac, 0x34,
	0xfe, 0x3e, 0x20, 0x7a, 0xa0, 0xbd, 0x7b, 0x54, 0x3a, 0x63, 0xf5, 0x8b, 0x90, 0x0b, 0xe6, 0x1c,
	0x89, 0xb2, 0x1e, 0xdb, 0xb1, 0x87, 0x8d, 0x92, 0x29, 0x83, 0xd4, 0x25, 0x1c, 0xc6, 0x1e, 0x46,
	0x67, 0xb4, 0xdf, 0xb9, 0xbb, 0x88, 0x92, 0x82, 0x55, 0x4b, 0xb9, 0x3a, 0x1e, 0x5e, 0xbc, 0xf7,
	0x69, 0x38, 0x4b, 0x50, 0xb0, 0x9a, 0xa3, 0x5a, 0x65, 0xcf, 0x10, 0x57, 0xb4, 0xd5, 0xd4, 0x13,
	0x07, 0x13, 0xbf, 0xdf, 0x4f, 0xdb, 0x1c, 0x8f, 0xbe, 0xb1, 0xed, 0x80, 0x68, 0x43, 0x5c, 0x53,
	0xe0, 0xa6, 0x8a, 0xa3, 0xee, 0xce, 0xd7, 0x96, 0x63, 0xf9, 0x53, 0xe8, 0xde, 0x4f, 0x89, 0x66,
	0xc8, 0x61, 0x70, 0xab, 0x96, 0xbc, 0xde, 0x62, 0x9d, 0x60, 0x1d, 0xc2, 0x1b, 0x56, 0xcb, 0x2c,
	0xad, 0x2b, 0xfc, 0x2b, 0xc3, 0x62, 0x60, 0x7f, 0xd2, 0xe5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0x6f, 0xf7, 0xc1, 0x62, 0x02, 0x00, 0x00,
}
